version: '3'

services:
  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db
